workflows:
  android-simple:
    name: Android Simple Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Build APK & AAB
        script: |
          chmod +x gradlew
          ./gradlew clean assembleRelease bundleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab

